# Generated by Django 5.0.4 on 2024-04-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_network', '0002_alter_seller_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='debt',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Задолженность перед поставщиком'),
        ),
    ]
