# Generated by Django 5.0.4 on 2024-04-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_network', '0003_alter_seller_debt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='debt',
            field=models.FloatField(blank=True, null=True, verbose_name='Задолженность перед поставщиком'),
        ),
    ]
